apiVersion: v1
kind: PersistentVolume
metadata:
  name: central-station-pv
spec:
  storageClassName: "manual"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/weather-system"
  claimRef:
    name: central-station-pvc
    namespace: weather-station

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: central-station-pvc
  namespace: weather-station
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "manual"
  volumeName: central-station-pv
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
spec:
  storageClassName: "manual"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/elasticsearch"
  claimRef:
    name: es-pvc
    namespace: weather-station

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  namespace: weather-station
spec:
  storageClassName: "manual"
  volumeName: es-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi