spring.application.name=demo

elasticsearch.host=localhost
elasticsearch.port=9200
logging.level.org.elasticsearch=INFO
logging.level.co.elastic.clients=INFO
app.storage.parquet.archive-dir=/home/amin/IdeaProjects/Weather-Stations-Monitoring-System/data/parquet_archives/