FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B -q

COPY src ./src
RUN mvn package -DskipTests -q

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/target/weather-station-1.0-SNAPSHOT.jar app.jar


ENV STATION_ID=1
ENV KAFKA_BOOTSTRAP=kafka:9092

CMD ["java", "-jar", "app.jar", "station"]
