spring.application.name=Centeral_Station
SERVER_PORT=8080

kafka.bootstrap-servers=127.0.0.1:9092
kafka.group-id=central-station-group
kafka.topic=weather
kafka.dlq-topic=dlq_weather_statuses
kafka.invalid-topic=invalid_weather_statuses